name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite execução manual

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Criar diretório data se não existir
      run: |
        if not exist data mkdir data
    
    - name: Compilar com PyInstaller
      run: |
        pyinstaller --name="SegundaDeLei" --onefile --add-data="templates;templates" --add-data="static;static" --add-data="data;data" --hidden-import=flask --hidden-import=jinja2 --hidden-import=sqlite3 --hidden-import=statistics --hidden-import=pandas --hidden-import=fpdf --hidden-import=werkzeug.serving app.py
    
    - name: Fazer upload do executável
      uses: actions/upload-artifact@v4
      with:
        name: SegundaDeLei-Windows
        path: dist/SegundaDeLei.exe
